name: Karate Integration Tests

on: [push, pull_request]

jobs:
  run-karate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Run Integration Tests
        run: mvn test
        working-directory: integration-tests
